PREPROCESSING_RESTRICTED = 'preprocessing_restricted'
SVM = 'svm'
DECISION_TREE = 'decision_tree'
RANDOM_FOREST = 'random_forest'
LOGISTIC_REGRESSION = 'log_reg'
ENSEMBLE = 'ensemble'
COUNT = 'count'
TFIDF = 'tfidf'
